### ISSUE TITLE
Move() Function

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1043]
move(<destination>)
    move(<target>,<destination>)

First syntax moves you to <destination> 
Second syntax moves  <target> to <destination> assuming you control <target>

Functionally very similar to tel(), but obviously doesn't require powers or roy/wizbits (except the latter syntax)

**Comment by HarryCordewener** [comment]
No. 

If you need this, create an `@function` on a wizard object and set a lock, and do it like that. 
Or use the tel_ok flag along with `@lock/teleport`.

This definitely does not need to be hardcoded.

**Comment by mike347** [comment]
If something being easy to softcode was a reason to not hardcode functions, then functions such as grab() would not exist.

**Comment by annelions** [comment]
I think that having this would be extremely handy in certain situations.

**Comment by Trinsec** [comment]
tel() to the exit would do the job, looks like.

**Comment by grapenut** [comment]
tel() with an exit as the destination used to work (and should again). The question here would be whether you would expect it to trigger all the verbs.

**Comment by mike347** [comment]
The intended use requires it to trigger the regular vergs if tel()ing to an exit (*success/*drop,etc), yep.

**Comment by HarryCordewener** [comment]
@grapenut It still works.

**Comment by talvo** [comment]
It does trigger verbs, yes. Honestly, I don't see much point in adding this.

**Comment by mike347** [comment]
I'll just add it to my local game as a custom function. It's handy because I want coded mobile (non powered) objects to be able to move through exits using a function call, even though @teleport/tel() is restricted to roy/wiz bits. Essentially move() would only be for moving through local exits without needing any powers or bits, I only brought it up here because I felt it was an oversight not having it and that it could be useful to other games.

**Comment by annelions** [comment]
If tel() is for wiz/roy only, then I still second the idea of a move() function for unpowered objects. A solution that doesn't require fiddling with the master room or wiz objects in any way.

**Comment by HarryCordewener** [comment]
The `tel()` function and `@tel` command can be used on oneself by unpowered objects, @annelions. 

`@tel me=exitname`
`@fo object=@tel me=exitname`

**Comment by annelions** [comment]
Not if you have it disabled or set everyone FIXED for RP purposes.

**Comment by mrsenile** [comment]
The issue with tel() is it follows both restrictions of @tel, as well as any @locks, FIXED, NO_TEL, or any other various lockdowns based on teleport.

When actually exit movement still works fine.  In such a situation, tel() wouldn't work on exits, as it would be restricted any number of ways.

The reason for move() is it would follow (and thus be restricted) by only what would restrict the goto/exit movement feature, nothing else.

I seriously don't see what the reservation of adding this is.  It follows the same vein of sideeffects that tel() <---> @tel would have, just adds further compatibility with other codebases, and literally is no more than a 5 minute addon to write the 9-12 lines of code required to make it happen.  It also will avoid certain restrictions that blocking @teleport would do, and still allow functionality to work in a functional way.

And if I hear a 'just write it in a command'.  Then I put to you to just remove tel(), pemit(), set(), and all the other sideeffects, because if you're going to use the excuse to just use commands for everything, you have just proven sideeffect functions to be a pointless and superflurous addition that obviously should be removed by those same merits.

**Comment by annelions** [comment]
Put much better than I was able to. This is exactly what I meant, yes.

**Comment by mrsenile** [comment]
Here you go.  I'll even make it easy for you.

function.c:  
```
{"MOVE", fun_move, 2, 2, FN_REG | FN_STRIPANSI},
```

fundb.c:
```
FUNCTION(fun_move)
{
  dbref thing;

  if (!FUNCTION_SIDE_EFFECTS) {
    safe_str(T(e_disabled), buff, bp);
    return;
  }
  if (!command_check_byname(executor, "goto", pe_info)
      || fun->flags & FN_NOSIDEFX) {
    safe_str(T(e_perm), buff, bp);
    return;
  }
  thing = match_thing(executor, args[0]);
  if (!GoodObject(thing)) {
    safe_str(T(e_notvis), buff, bp);
    return;
  }
  if ( !controls(executor, thing) ) {
    safe_str(T(e_perm), buff, bp);
    return;
  }

  move_wrapper(thing, args[1], pe_info);
}
```
