### ISSUE TITLE
Issues with Configure

### ISSUE THREAD

**Issue by mcgiwer** [pennmush/pennmush#1068]
Please create that OpenSSL is not a required dependency, but it's a optional one. Since OpenSSL-dev package has been stopped to be distributed for Ubuntu (thru repositories), it's hard to compile it. Additionally, the "Configure" badly detects the existing (installed) OpenSSL (and manually added the openssl folder with the header files) and OpenSSL is not defaultly included as part of Pennmush package

**Comment by aiviru** [comment]
It looks like Ubuntu calls the package libssl-dev ( http://packages.ubuntu.com/wily/libssl-dev ).

**Comment by aiviru** [comment]
Managed to build fine on a fresh install of Ubuntu Server 14.04.4 LTS after installing the following packages and their dependencies:

git libssl-dev libpcre3-dev build-essential

**Comment by mcgiwer** [comment]
since 14.10 (and above) there is no openssl-dev and mentioned by you libssl-dev has helped. It would be nice if to pennmush were all dependencies files included instead the of need to install them (except build-essential related packages)

**Comment by shawnw** [comment]
OpenSSL is a mandatory dependency. It's not going to be included with Penn. There is no way that would be remotely feasible.  

What might be useful is making a PennMUSH package for a few popular package management systems, so that installing the PennMUSH package installs any missing mandatory dependencies. I think somebody did that in the distant past with Debian, but didn't keep it up to date.  Even then, different OSes that use the same package manager might have different names for the package(s) that provide a library. It's a royal pain.

I'll see about updating documentation that refers to openssl-dev as a possible required package to also mention libssl-dev.

**Comment by mcgiwer** [comment]
I can tell you that for all Debian based (to with count also Ubuntu series) this packages are usually intalled following ways:

1. Command line (simplest version):

* apt-get install <package name>
* dpkg -i <package name>

2. Common managers:

* aptitude (bash based) - need to be installed
* synaptic - in earlier versions it was included, but now it need to be installed
* software-center (build-in into ubuntu)

**Comment by tkrajcar** [comment]
The PCRE and SSL requirements are [documented in the INSTALL doc](https://github.com/pennmush/pennmush/blob/master/INSTALL#L76-L85), thanks to some improvements @shawnw made in 6fa63eae9d81c53d711827470bcd986d20e2d6a5, so I think we're good here.
