### ISSUE TITLE
Extra %R's in LISTEN * when listening for help

### ISSUE THREAD

**Issue by tylisirn** [pennmush/pennmush#1085]
When a THING with LISTEN: * performs a command to view help, the output contains extra carriage returns resulting in double spaced output. Eg:

test(#12714T)
Type: THING Flags: 
AHEAR [#5530$]: @emit %0
LISTEN [#5530$]: *
TEST [#5530]: $test:@emit testing!; help help; @emit end test;

results in output like:

>This is the index to the MUSH online help files.
> 
> 
> 
>  For an explanation of the help system, type:    help newbie
> 
>  For a walkthrough of PennMUSH systems, type:    help getting started
> 
> 
> 
>  For the list of MUSH commands, type:            help commands
> 
>  For the list of MUSH topics, type:              help topics

etc...

**Comment by tylisirn** [comment]
There should be more linefeeds in the quoted output, but markdown ate them.

**Comment by talvo** [comment]
Finally figured out the cause; it's not related to `@listen`, but to the way `help` works. Because it's reading (potentially) huge(ish) chunks of data from a text file, it sends them in bits X characters long, without linebreaks in between (but the bits may contain linebreaks). When you're a player, that all goes into a buffer and gets sent to you at once anyway, so it looks no different to anything else. When you're a non-player, you get each chunk one at a time, triggering the listen repeatedly with small bits of text.

(In this context, "huge(ish)" means "quite possibly bigger than BUFFER_LEN".)
