### ISSUE TITLE
OpenSSL OSX El Capitan Error

### ISSUE THREAD

**Issue by jaybird1905** [pennmush/pennmush#1118]
Hey guys,

I get part way through the install when it bombs out on me:
`checking for pkg-config... no
checking for openssl/ssl.h in /usr/local/ssl... no
checking for openssl/ssl.h in /usr/lib/ssl... no
checking for openssl/ssl.h in /usr/ssl... no
checking for openssl/ssl.h in /usr/pkg... no
checking for openssl/ssl.h in /usr/local... no
checking for openssl/ssl.h in /usr... no
checking whether compiling and linking against OpenSSL works... no
configure: error: The OpenSSL library must be installed to run PennMUSH.`

I'm running the latest version of El Capitan on OSX. 

I've tried uninstalling and reinstalling OpenSSL through Homebrew with no avail. Googled around but haven't really found anything.

Any help would be greatly appreciated!

Thanks,
Jay

**Comment by talvo** [comment]
Update: We got this working on `M*U*S*H`, but then ran into an issue with symbols for `EVP_MD_do_all` not being found. After a long while of attempted debugging we have up and just commented out the check that enables fun_digest. Might be worth making that a configure check, instead of relying on the OpenSSL version, since it seems it's only available on MacOS if you do a lot of custom compiling and wrangling, @shawnw ?

**Comment by shawnw** [comment]
Done. Commit 7dab08be
