### ISSUE TITLE
Incorrect ansi codes after recent update

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1147]
Recently some changes were made to ansi colors. After merging the latest commits, this happened:

https://imgur.com/a/cKVXs

The color used for that channel was +deepskyblue2, which gave a hex color of #00b2ee, but now #00b2ee maps to that dark pinkish color, and +deepskyblue2 maps to #00afd7.

This has broken (albeit cosmetically) monkers and channel names on my game.

`th deepskyblue2 went from [ansi(+deepskyblue2, this)] to [ansi(#00b2ee,this)]. Not only in channel names, but also in monikers.
`
Is this an intended change, or a mistake/bug?

**Comment by talvo** [comment]
```
#4] th colors(#00b2ee,xterm256)
39
#4] @shut/reb
GAME: Reboot w/o disconnect by Mike, please wait.
GAME: Saving database. Game may freeze for a few moments.
GAME: Save complete.
GAME: Reboot finished.
#4] th colors(#00b2ee,xterm256)
138
```

**Comment by mike347** [comment]
I've added more broken color screenshots to the above link.

What was once a darkgray color is now coming up purple. Maybe these changes need to be reverted and properly tested?

**Comment by shawnw** [comment]
That's interesting. I'll look into it tonight.

**Comment by shawnw** [comment]
Caused by some of the extra color dictionaries that were tossed in having colors with the same name but sometimes wildly different values (There are three different versions of "maroon" in the provided Graphics::ColorNames schemes, for example...). Going to go back to just X11 and xterm256 colors.

**Comment by shawnw** [comment]
It also doesn't help that even in the individual Xterm256 and X11 color listings, there are duplicate color names with different values. Xterm colors have two DeepSkyBlue3 (+xterm31, +xterm32) and **three** DeepSkyBlue4 entries (+xterm23, +xterm24, +xterm25), for example.  With Xterm duplicates, all the +xtermNN versions work, but only the first one is used for a +colorname.

The old genrgb.pl code: Uses +xterm0-+xterm255, no xterm color names, just X11 names.

Current code: Outputs +xterm0-+xterm255, plus the xterm color names. Outputs HTML, Netscape, Windows, X11 names only if the name hasn't been used already.

XTerm +deepskyblue2 is 0x00afd7, X11 is 0x00b2ee (Which gets mapped to +xterm39, +deepskyblue1 0x00afff). So that's the source of that issue.

New code: Outputs +xterm0 to +xterm255, outputs X11 names, then outputs xterm names that don't have X11 duplicates (All 6 of them).

See if it helps.

**Comment by mike347** [comment]
Some colors are fixed, but some are even more broken now.
`th [ansi(#1b1b1b,-)][ansi(#363636,-)][ansi(#515151,-)][ansi(#6c6c6c,-)][ansi(#878787,-)][ansi(#a2a2a2,-)][ansi(#bdbdbd,-)]
`
Should produce a colored line starting from dark gray and ending in lightgray/white. It now has several other colors, including cyan, pink and yellow.
Checking the hex codes  above something like http://htmlcolorcodes.com/ will show you the proper color, then compare that to what ansi() provides, you'll see what I mean.

**Comment by shawnw** [comment]
I don't think I touched anything in the mapping of RGB values to Xterm256 colors. Which means it's probably something really stupid...

**Comment by shawnw** [comment]
Yup, it was something stupid.
