### ISSUE TITLE
lsearch(), etc. needs prefix matching

### ISSUE THREAD

**Issue by mike347** [pennmush/pennmush#1154]
A recent change to lsearch().. and maybe other functions, I've not checked, replaced string_prefix() with strcasecmp(). For softcode functions, for backwards compatibility, they should stay using string_prefix().

E.g. 

```
lsearch(all,type,thing)
-->Invalid type
lsearch(all,type,player)
-->Invalid type
```

This breaks a lot of things in my game, simply because of using 'thing' instead of 'things', 'player' instead of 'players', etc.

**Comment by talvo** [comment]
I would honestly like to see that entire commit reversed. I really don't see the point for it; the issue was that the websocket patch removed an empty-string check, and stuff broke when that empty string was passed to string_prefix in that one particular place. Removing string_prefix with a sledgehammer throughout the entire source was overkill; we just need the empty-string check back there.

**Comment by grapenut** [comment]
Yeah, I agree with Mike. The empty string problem was fixed in another commit, so this was not necessary.

**Comment by shawnw** [comment]
I thought I'd accounted for all the places where a prefix match was desirable. Blah.

I'll roll back most of it.
