### ISSUE TITLE
Wizards and @force

### ISSUE THREAD

**Issue by Kimojuno** [pennmush/pennmush#1159]
Right now it is possible for one wizard to @force another wizard to do something. For example, @pcreate and other commands. This seems like a potential security issue. Obviously all @force uses can be logged on the server and verified for later review but it just seems like a potential issue that should be resolved.

**Comment by mrsenile** [comment]
Why would it be a security issue as each wizard has no more or less access to every other wizard?

Whatever a wizard could @force one wizard to do they could do themselves, no?

**Comment by Kimojuno** [comment]
While it's true that all wizards can do the same thing, being able to @force someone to @mail, for example, or @wall an illicit or otherwise hurtful message could damage someone's reputation on the MUSH. Mind you, I am aware that's a worse case scenario.

Obviously, all wizards should be trustworthy and not do such a thing. On the other hand, I've also seen people ragequit or try to hurt others reputation. I suppose the term security issue might not completely fit, but there is a potential for abuse if one wizard can @force another wizard to do a command.

Mind you, again, I am aware that logs are kept, but not everyone would immediately consider checking whether a wizard was @force to do whatever they are accused of doing.

**Comment by mrsenile** [comment]
I can understand your concern, really I can.

However, this is one of the main reasons you always keep backups of your mush.  Acts of god, human error, and the rare rage-quitting wizard are all good examples on why you want backups.

And honestly if a wizard was to rage-quit or be in a position to no longer be trustworthy, there's far far more concern than @force.

&ATTRIB *user=[mailsend(%0,%1)]
think u(*user/attrib,user-to-abuse,nasty message)

All done without @force.  So now you have to disable all mail functions and attribute setting.

@dolist lnum(1,1000)=@nuke #[##]

So now you have to remove all destroy abilities from the wizard as well.

@dolist lnum(1,1000)=@cpattr #[##]/*=#[sub(##,1)]

So not only setting attributes, but now any possible command that modifies attributes, like @cpattr, @mvattr, @edit

@dolist lnum(1000)=@pcreate Spam##=##

So now you have to remove all creation tools from a wizard as well.  @dig, @open, @create, @pcreate and similar functions...

Honestly if your concern is a wizard is going to abuse their ability, don't set them wizard.  Otherwise, frankly most tools at their fingertips will be a problem.

**Comment by grapenut** [comment]
The same sort of spoofing could be achieved by @naming things. Name the other wizard to blah, name yourself otherwizard, send mail, put the names back.

**Comment by talvo** [comment]
Indeed; wizards control everything in the db (except God), so don't give it to people you don't trust. Restricting `@force` wouldn't really achieve anything, as others have said, because total control of the db means you can just `@trigger`, ufun, set `$-commands`, etc, to achieve the same nefarious ends, should that be your aim.
