### ISSUE TITLE
ERROR: Invalid UTF-8 sequence

### ISSUE THREAD

**Issue by ray73864** [pennmush/pennmush#1168]
I get this all the time, a good example is this page: https://www.dominos.com.au/inside-dominos/technology/delivery-guarantee

If I copy/paste the first paragraph into the Potato input window and try to mention it on-chan, it'll return that error, it appears it's throwing up at the apostrophe in the word Domino's, and also at the hyphen in the last part of the paragraph.

Converting them to their penn-happy versions makes penn a very happy chappy.

Mike says Penn announces it does Unicode, Potato negotiates that fact, but Penn does a bad job of the whole thing.

It would be nice if Penn either gracefully ate the bad chars, or if it just converted them on the fly, or, if none possible at all, at least say what chars it coughed up a lung on :)

**Comment by talvo** [comment]
Or just stopped claiming to do unicode when it doesn't really do unicode. No support is better than lying and giving bad support.

**Comment by shawnw** [comment]
Penn understands unicode but only accepts characters in the basic latin and latin-1 blocks (For now).

Replacing codepoints outside of that range with ? would probably be better than errors, though... hmm.

**Comment by talvo** [comment]
I would like to see:
a) Yes, definitely put in a ? (or, second best, just eat unrecognised characters) instead of rejecting the whole input. But WAY more importantly
b) stop announcing to clients we support unicode when we don't!

This conversion is fine for things like Banana, which don't negotiate charset and just send utf-8. But clients that CAN negotiate.. well, that's the entire point of the negotiation, so they send what we support. And we really, really don't support utf-8.

On top of that, Potato (maybe other clients too?) will automatically convert a bunch of unicode characters to good latin-1 alternatives when you connect to a latin-1 game and then try and send unicode. But this no longer happens, because Penn is negotiating support that doesn't exist.

**Comment by shawnw** [comment]
Went back and double checked the code, and if you get the `ERROR: Invalid UTF-8 sequence.` message, it's because the mush got a line of text that was supposed to be encoded in UTF-8 that it thinks isn't. Unicode characters outside of the latin-1 range are already turned into question marks.

Got an example of input to a mush that does generate this error?

**Comment by shawnw** [comment]
Okay, so here's what's happening with that invalid utf-8 sequence error:

The smart quote in the word Domino’s (And other places) is unicode character `U+2019`. Encoded in UTF-8, that's the three bytes `0xE2 0x80 0x99`. Potato seems to be only sending the 0xE2 byte, and in its packet debugger, the character shows up as 2019 instead of the UTF-8 bytes: `... 6E 6F 2019 73 20 ...`

In other words, it's not my (Or Penn's) fault for once. The mush is getting and detecting garbage. The question is... how much should it try to recover from said garbage?
