### ISSUE TITLE
Improving the main event loop

### ISSUE THREAD

**Issue by shawnw** [pennmush/pennmush#1174]
The main game event loop currently uses poll() (WSAPoll() on Windows) to tell when sockets can be read or written to and handles i/o as appropriate. shovechars() in bsd.c has the relevant code.

I'm thinking about restructuring it to be more modular and use more efficient polling mechanisms epoll() on Linux, kqueue() on BSDs, and Windows i/o completion ports (Which we used once many years ago in the Nick Gammon days but dropped due to bit rot), falling back to poll() on other OSes for anybody who's still using, say, a commercial unix. This would in particular would make it easier to support info_slave and ssl_slave on Windows, which is another future project idea.

Also thought about using libevent, which does all this, but that would be a bigger change to control flow than I'm willing to make right now. Plus a new mandatory dependency when it's optional right now...

**Comment by talvo** [comment]
Please no more mandatory dependencies. Having the option of using libraries for better featuresets is great, but we already have a bunch of people who've given up on Penn and switched to Rhost or elsewhere because Penn requires installing loads of crap they don't have on their systems (particularly on shared hosting where adding things is problematic) - and that's way more common crap than libevent. Ripping out perfectly functional code and replacing it with stuff that requires another, not especially common dependency just seems foolhardy to me.

**Comment by mike347** [comment]
My question is, what is the benefit? There are risks associated with such a big change as messing with the main loop, what will be gained by doing it?

I also agree with Mike that we do not need more mandatory dependencies. If anything, we need less.
Change for the sake of change isn't always a good thing. The string_prefix() debacle should be a reminder of that.

**Comment by mrsenile** [comment]
Speaking as 'that other codebase' I can confirm talvo's commentary making people change to Rhost.

Honestly, there would be more conversions if it was easier to convert a Penn db to a Rhost db from what I've been asked already.

The first stamped run came several years ago when the hardcode update broke a fair amount of softcode compatibility.  People hate change.  Full stop.

The second stamped run came when dependency hell and more issues with 'compiling penn' came into the picture.  Not as big as the softcode one, but it's a telling argument.

So I'm with talvo and mike on this.  I'm all for improvements where there can be, but not at the cost of backward compability where the cost outweighs the benefits.

From my study the only benefit for epoll to poll is the better handling of multiple ports at the same time, and arguably (unproven from what I've seen) faster response time on the poll to response.  It apparently makes a much bigger difference on what is considered a large number of port connections.

Let's face it.  Mush will never get 'a large number of port connections'.  I understand that similar to MQ or Tibco where you're getting in the ballpark of 8000+ connections every few minutes.   The second issue is mush isn't multi-threaded.  It can't take advantage of the more advanced features **_anyway_** without a serious redesign of, well, everything.

I honestly don't see much benefit to this unless you can:
1. guarantee 100% backward compatibility
2. a null requirement of additional resources to use
3. that the work involved won't be greater than the cost and effort to put into it
4. if it actually buys, well, **anything**.

Just food for thought.

**Comment by annelions** [comment]
How many people even use Penn on Windows for an actively running game? That seems like a lot of work to support edge-use cases. 

I have no idea about the dependencies, but more always = bad.

**Comment by talvo** [comment]
A lot of people used to like being able to run the precompiled binaries for learning or setting things up without having to acquire and learn how to use linux hosting. But it's been a long, long time since precompiled binaries were regularly supplied, and because of the existing dependancies, compiling on Windows yourself is a major hassle.

**Comment by annelions** [comment]
I realize that. But that's not an active game and, thus, has very little need for info_slave, as I understand it. Isn't that the part that fetches the hostname for a given IP address? And SSL is almost certainly not needed to dev on a local machine.

**Comment by shawnw** [comment]
Welp, this idea seems to be firmly opposed. Sticking with poll.

**Comment by talvo** [comment]
I wouldn't say that I'm against it (though I'm no position to say what the benefits are), as long as anything new is used purely when the libraries are available, with the current method as a fallback. Just opposed to libevent (or something else that isn't widespread/available by default) being a requirement, rather than an option.
