### ISSUE TITLE
libcurl timeouts?

### ISSUE THREAD

**Issue by captdeaf** [pennmush/pennmush#1232]
`@http` can hang indefinitely in several situations.

Maybe add a timeout to the curl call? And a maximum body length, if possible? (One situation is shoving infinite data down the pipe)

**Comment by shawnw** [comment]
It's *supposed* to have timeouts set for long or slow responses. Maybe I misread the documentation about those options?

**Comment by captdeaf** [comment]
Sorry right, to be clear:

Timeout is for connecting/resolving/etc. I'm suggesting an overall timeout, e.g: in bsd.c, if `@http` doesn't finish (successfully or un-) after a configurable timeout (say, default 10 seconds?), then kill it and continue w/ what we have.

One example of hanging: I have a foo.cgi that just prints infinite foos. Not only does `@http` never return, but just starts inhaling memory.

**Comment by shawnw** [comment]
Okay, I found another option for setting the maximum total time used by a connection (The option I had set was only for timing out slow connections). 5 minutes sound good? Or think that's too much?

Also found a way to abort after getting too much data, which I'll be setting to `BUFFER_LEN` bytes, since we can't do anything with more than that. (This will be a lot more useful when the work I'm doing in the unicode-icu branch to get rid of fixed-length strings starts to come together into something usable. We can raise the max data a lot at that point.)

**Comment by captdeaf** [comment]
Both of those sound like an ideal fix.

5 mins sounds a bit on the long end for 'small' requests. Maybe configurable, with a 5 or 10 second default?

BUFFER_LEN in data is good - If that includes headers, though, maybe 2*BUFFER_LEN just so it can split?

**Comment by mrsenile** [comment]
BUFFER_LEN likely won't handle an infinite loop sending nulls, but the timeout handler should theoretically works as per libcurl's documentation it actually sends an alarm().

Then it's just a matter to make sure that alarm call doesn't twig out any internal signal handlers within the mush :)

**Comment by shawnw** [comment]
I went with 5 minutes because that's also the default timeout for connection attempts and it seems tidy to have both be the same. It really does seem like a really long time, though. Maybe a minute instead? I don't think it needs to be user-configurable, or if so, via a define in the source, not a config file thing. That just seems like overkill.

The length check only counts content, not headers. (And it's [not using signals](https://curl.haxx.se/libcurl/c/CURLOPT_NOSIGNAL.html) for timeouts).

**Comment by shawnw** [comment]
Closed with PR #1234
