### ISSUE TITLE
Reminder for Mike

### ISSUE THREAD

**Issue by jetfire158** [pennmush/pennmush#1271]
add reference to HELP WILDCARD in HELP STRMATCH, and possibly other help files for functions/commands that can use wildcards. 

also notes about escaping wildcard characters in these functions because it usually requires two backslashes instead of just one for a reason I didn't quite understand. ;)

**Comment by talvo** [comment]
It's because the wildcard matcher needs to see the `\`, but `\` is a special character in softcode, too, so if you don't double it up, the softcode parser eats it before the wildcard matcher sees it.

Added a note and example about that to HELP WILDCARDS, and referenced that from a bunch more places where it would be of interest.
