### ISSUE TITLE
[Feature request] More user customizable Pennmush

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1359]
I would like to propose to make that all pathes, instead of beeing hard coded, would be moved into the config file. This way, user could freely customise Pennmush to it's need's, by (for example) setting the directories as he/she would like, within the "game" directory.

**Comment by ray73864** [comment]
Sounds to me like you want 'make customise'.

'make customise' uses a single source code tree to create lots of games, so instead of having 'pennmush/game' you could have 'pennmush/game1' and 'pennmush/game2', etc...

**Comment by mdziczkowski** [comment]
@ray73864

**Definition of used bellow terms**:

-> Root - the "game" folder of Pennmush instalation

** Reply **

not exactly. I wanted that any folder of the game could be freely moved into any sub-folder inside of the Root, without any impact on the game

**Comment by tkrajcar** [comment]
>I wanted that any folder of the game could be freely moved into any sub-folder inside of the Root, without any impact on the game

Why?

**Comment by mdziczkowski** [comment]
I wanted to change the folder structure inside of the "game" folder to customize it to the needs of the server (to make the administration more simple)

**Comment by HarryCordewener** [comment]
You can use symlinks for that, last I recall.

**Comment by mdziczkowski** [comment]
it would mess up the folder structure and I wanted to make it as simple as possible

**Comment by HarryCordewener** [comment]
How would symlinks mess up the folder structure? Keep in mind, you are basically requesting a significant change and notable dev resources for something that has a possible solution. It'll be a very hard sell just because it doesn't have good folder aesthetics.

**Comment by mdziczkowski** [comment]
I think that a better solution would be to make that the location of the folders were read for example from a separate config file (for example: "mush.dir"). It would solve it until someone think something better out for optimizing the folder discovery

**Comment by HarryCordewener** [comment]
The ratio of amount of effort vs gain here seems extremely low here. You are free to submit a pull request if you want to do this work, but 'folder discovery' is optimized enough that this borders on being a bit silly.

**Comment by talvo** [comment]
You can customise a pretty sizable chunk of file locations. mush.cnf holds paths for a great many things and the location of that file is easily customised too. I have seen several games where absolutely everything sits outside the directory where the source/executable live. So I would suggest exploring more fully if what you want is actually possible already.

If there's a specific file/set of files you've investigated and found can't be moved, please reopen the ticket and let us know what specifically and why being able to move them would be useful. However, chances are if it's not a quick fix it's unlikely to happen due to minimal gains for the time required.
