### ISSUE TITLE
[Feature request] Database creation and management tool

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1362]
I wanted to request a build into Pennmush tool, with would allow to create all needed databases for the game (basing on their names given in the "mush.cfg" file) within the "data" folder.

This would help to easier create it and start the server

**Comment by HarryCordewener** [comment]
They get created on the server started, which then does a few tests as well. 

What's the actual goal to this request? And why do the files being created on startup not serve your needs?

**Comment by mdziczkowski** [comment]
> They get created on the server started, which then does a few tests as well.

Actually, by each start, Pennmush attempt's to read the input database (with is Not beeing created. Instead of it, it creates a "crash_db" with contains a "world" and many things with make the database look messy and hard to manage). 

By the way... it would be good to optimize it's structure and make it more "admin friendly".

> And why do the files being created on startup not serve your needs?

Not at all because:

- as mentioned this answer on the first part of your question, the actual structure is messed up and hard to manage, plus the administrator donsn't have any control about what becomes created ("God" user, world, etc.)
- because of above, the manual edition of database is very annoying, difficult and takes too long

**Comment by ray73864** [comment]
It's a 'minimal' DB that gets created on startup, not a crash_db.

And it's served people well for the last 20 or more years, since it is designed for newbies.

When the minimal DB is created, it gives a newbie everything they need to get started, a god character for managing the game (creating new wizards, etc...), a master room for global commands, and a starting room.

RhostMUSH, PennMUSH, and TinyMUX all create minimal DBs on startup if the main DBs don't exist.

**Comment by mdziczkowski** [comment]
> It's a 'minimal' DB that gets created on startup, not a crash_db.

sorry, I had used the shorten name of the variable from mush.cnf file. The file with the "minimal world" as you name it has the name PANIC.db (with is represented by the "crash_database" variable) and as I mentioned previously, the server attempt's  every start to read an not-existing database (represented by the "input_database" variable)

> And it's served people well for the last 20 or more years, since it is designed for newbies

It's quite discussable if the database is "newbie friendly" ;-P

As I mentioned earlier, the tool would make the process of world creation and management faster and easier. I cannot imagine myself to manually edit a database with would count for example hundreds lines of code when the world grow up ;-p

By the way, as far as I remember, some MUD's already have a world creator and manager implemented

**Comment by HarryCordewener** [comment]
This is not a MUD. Almost all coding for PennMUSH gets done on-game, not by editing the hardcode. I assume you are aware of this?

**Comment by mdziczkowski** [comment]
> I assume you are aware of this?

yes, I am. I just thought to make the adminstration of the world easier with a graphical or console tool, since the worlds can grow up to huge sizes and it's getting then very difficult to manage this database by editing the file manually in a text editor

**Comment by HarryCordewener** [comment]
Nobody would manage the database by editing the file manually in a text editor. That is not how PennMUSH is maintained by... anyone.

**Comment by ray73864** [comment]
As @HarryCordewener has just said, Penn is not maintained by editing the DB files manually, that would require shutting down the server, editing the DB, bringing the server up and hoping for the best.

All maintaining of the game is done by logging into the game as a wizard character (or as GOD if you need to do something that only GOD can do) and doing stuff.

Such as creating softcoded systems, creating new builder characters for new areas, etc...

This isn't a MUD :) We aren't that draconian.

**Comment by mdziczkowski** [comment]
@HarryCordewener 

> Nobody would manage the database by editing the file manually in a text editor.

yeah, it would be a pain in *** to do that and would turn the persons live to hell while doing that ;-P

@ray73864
> All maintaining of the game is done by logging into the game as a wizard character (or as GOD if you need to do something that only GOD can do) and doing stuff.

I agree, but mostly the things from the database (like: dbref, names, attributes, etc.) aren't normally displayed and the Wizard, Admin or even God may not know the reference to any place, object, etc. in the whole World

**Comment by ray73864** [comment]
You 'examine' the object, that'll show you the dbref, names, and attributes.

This is how people have been managing their worlds for years.

I for one ran a server that had almost 30,000 objects on it, according to @stats in-game: 28650 objects = 6673 rooms, 13666 exits, 7528 things, 582 players, 201 garbage.

Never had any issues maintaining the game in-game, and not once did I ever have the need to edit the DB file manually.

@search, @locate, examine, etc... all work perfectly fine.

**Comment by talvo** [comment]
Wizards do see the dbrefs of everything by default.

The MUSH will load a panic db if there is one, but that's the only case where you've had an existing world and something has gone wrong while it's running, so that's just your latest db. If you're running a new clean game and don't have a db, the MUSH will create one with just 3 objects: a single generic room (`#0`). the God character with no password (`#1`) and the master room (`#2`). You get totally empty chat and mail databases as well. At that point you're free to create or customise as much as you want.

If you want a tool to help you build a world outside of the MUSH, there are some (though I don't think anything recent) but that is outside the scope of PennMUSH itself.

**Comment by mdziczkowski** [comment]
@talvo Ok, thanks. I have a question related to the structure of the generated "minimal world": could it be more simple?

As default, the "simple world" database's file structure containin the following schema:

- database header
- list of aliases (I don't think it's much required in this file, since it's a copy of what server provides)
- something I don't know the role of
- first room
- first user (God)
- master room

Starting from the "first room", until the "master room" position of the list, there are too many parameters put inside as default.

I understand that you wanted to try making it to work "out of box", but the current structure complicates the file and increases only it's file. The additional problem with it is that the structure is not too well documented. There is no file in the data folder with would explain how the database files are (or should be) build, etc.

**Comment by ray73864** [comment]
You aren't supposed to modify the database outside of the game.

Minimal world creation is here: https://github.com/pennmush/pennmush/blob/41a3c01fdebd8b65654327f7bc41e1fc42f10ca6/src/db.c#L2748

In that, the function runs the standard new_object() function call which sets a whole lot of defaults on its own, the function then sets up various locks, etc...

All of these things are required by the game when it is running so that it knows how to behave.

But again, all modification is supposed to happen in-game, not in a text editor outside of the game.

When the game starts up with a minimal db, it gives you everything you need to start with, when you log into a character, a room must exist, you can't just log into nothingness, hence why "Room Zero" is created, "Master Room" is created because it is needed by mush.cnf to say where global commands live (you create objects, put commands on them, and stick them in this room if you want them to be accessible all over the mush).

**Comment by ray73864** [comment]
A lot of the starting stuff that you see are the flags and their aliases, because flags are physically stored in the DB.

Flags used to be stored in memory only, but that meant that if you deleted a flag, created a new flag, etc... in-game, the flag would just come back when you shutdown and brought the game back up again.

By storing the flags in the DB, you can use @flag/add, @flag/delete, etc... in-game to create or delete flags (Can only be used by GOD from memory), these flags become persistent across reboots and shutdowns.

**Comment by mdziczkowski** [comment]
Would not be a good idea (for security matters) to ask the user by the first server start about the name (and password) for the "God" user instead of using the hard coded one?

**Comment by ray73864** [comment]
What security issues?

It's literally the first start of the server, at that point, only the person firing up Penn for the first time should know the servers IP address and port number.

On ST:F, we sitelocked GOD to localhost, the only way to log into the godchar was to open an SSH tunnel and access it that way.

On other games they might randomise GODs password after the server has come up and then utilise things like 'gdb <netmush pid>' and set a breakpoint on the password check in order to log in as GOD on the rare occasions that they need to log in.

Pretty much once you have the server up, you set gods password, create yourself a secondary wizard character and then never log into god ever again unless you need to set another player wizard, or create new flags, etc...

Most things that god can do any wizard char can do with only minor exceptions.

**Comment by mdziczkowski** [comment]
Let's assume such situation: I decided to run Penn on a VPS, where I run other services, so it's accessable from internet. I need to modify the server with would need temporary allow access to God from any address, since I have a dynamic assigned IP in my network.

Since it's known, that the hard coded "Administrator" name is "God" and it does not have any password, it would be easy for anyone to access it and take over of the Penn server and if he's/she's lucky then cause a DOS attack thru it and make the VPS unresponsible and/or other damages (like data leak or future secuity matter problems, including in the worst case the suspension or termination of the VPS)

**Comment by MrWigggles** [comment]
That would be an outstanding number of happenstance to allow that to
happen. On the level of a Dan Brown novel. The attacker would need access
to your VPS. Wait for the Penn game to built, log onto it with the right
address, which I guess they have for already being on the compromised VPS.
Then beat you to logging into the game yourself. I'm not sure why, if this
plot happen you couldnt just terminate the game once you couldnt log on.
If that happen to a game I was making. I'd probably assume it built wrong,
toss it out and try again after bugging hardcode why how I fucked it up.

A real secruity issue, is a Wizard who decides to blackmail the game by
spaghetti important softcode brick the game or wiping every player object
minus God. Not that I've ever had that happen to me.

**Comment by annelions** [comment]
The very first thing you should do on login is to change the password for God. If you do that, the chances of having the God character compromised is pretty much nil. MrWiggles has it right that the real security issue is an ordinary Wizard doing something to the database.

**Comment by ray73864** [comment]
> 
> Let's assume such situation: I decided to run Penn on a VPS, where I run other services, so it's accessable from internet.
> 

OK, Not an uncommon thing to do, so nothing wrong there.

> I need to modify the Penn server with would need temporary allow access to God from any address, since I have a dynamic assigned IP in my network.

Still not a problem happens all the time.

> Since it's known, that the hard coded "Administrator" name is "God" and it does not have any password, it would be easy for anyone to access it and take over of the Penn server.

Why didn't you change the GOD password the moment you fired up the game with a minimal DB?
The moment you fire the game up, the first thing you do is connect to it, either via localhost with a telnet client or using a mush client (such as Potato, MUSHClient, BeipMU, SimpleMU, etc...) and then @password or @newpass the GOD character. Only a fool leaves it with no password.

> If he's/she's lucky then cause a DOS attack thru it and make the VPS unresponsible and/or other damages (like data leak or future secuity matter problems, including in the worst case the suspension or termination of the VPS)

Nope, the most they can do once they break into the GOD character of a PENNMUSH game is to hurt the game itself. They won't be DOSing the server anytime soon, they would need root access to the VPS for that, the game and the VPS are not tied together when it comes to access.

If your game gets compromised, you log into your VPS and shut down the game itself.

**Comment by talvo** [comment]
A few things:

As someone else mentioned, the database is not meant to be hand-edited. It's in plain text, so if you're careful you certainly can do so, but it's not the general intention. You aren't wrong that the format isn't well-documented, and there's no harm in it being, but because writing documentation takes time and it's something people rarely do, it's never been prioritised. (The few people who have wanted to edit a db by hand generally have years of experience and a large db which requires them to for some reason, and if you're familiar with how Penn's objects, etc, work, the db format is reasonably self-explanitory as all the values have textual labels.)

With regards to your security concern: As others have said, you're giving a lot of worry to an incredibly unlikely and minor occurance. On the off-chance that someone just happened to be trying random ports on random servers, knew what a MUSH was, recognised a MUSH was running (where one hasn't before), tried to connect to God without a password, and managed to log in in the few seconds it takes you after getting the MUSH and running to log in yourself and change the password - the worst they can really do is lock you out of God, maybe generate some big log files. But you'd notice immediately that you can't get into God or that someone else is also in and be able to just shut it down from the server, and remove the db and start over. Please note: I have literally not once ever heard of this happening. 

Being able to customise the name would make no difference as you can log in via the dbref. God's dbref is hardcoded as `#1` and customising this, especially in a db that starts essentially empty, is not practical or worthwhile. While you could allow an option to provide a starting password, again, I don't see any need given the drastically unlikely series of events needed for this 'issue' to occur, and if anything having it popped down in a config option is a bigger risk than anything. It could be given on the command line but it's not worth the time it would take to add the functionality, in my opinion. 

There is also a tool with Penn which can edit the db and reset passwords, by the way. If you're really concerned, you can use access.cnf to ban anyone from connecting, restart the game, shut it down from the terminal, and use the tool to set a password for God before you bring the game up open to the public.

However, a prompt in the room desc of Room Zero to set a password for God on login would be a quick and easy option for making sure brand-brand-new MUSH admin know they need to do this. (Though it is also documented in the howto that tells them how to log into God in the first place, I'm sure.)

**Comment by mdziczkowski** [comment]
@MrWigggles

> That would be an outstanding number of happenstance to allow that to happen. On the level of a Dan Brown novel. The attacker would need access to your VPS. Wait for the Penn game to built, log onto it with the right address, which I guess they have for already being on the compromised VPS. Then beat you to logging into the game yourself. I'm not sure why, if this plot happen you couldnt just terminate the game once you couldnt log on. If that happen to a game I was making. I'd probably assume it built wrong, toss it out and try again after bugging hardcode why how I fucked it up. A real secruity issue, is a Wizard who decides to blackmail the game by spaghetti important softcode brick the game or wiping every player object minus God. Not that I've ever had that happen to me.

Not exactly. He/she does need to attack directly the VPS. It's enough to connect (with terminal) to the server's URL with the port 4201 with a console to connect it

@ray73864 

> Why didn't you change the GOD password the moment you fired up the game with a minimal DB?

I usually would connect to VPS thru ssh and prefer to connect to the Penn with a separate client

> Nope, the most they can do once they break into the GOD character of a PENNMUSH game is to hurt the game itself. They won't be DOSing the server anytime soon, they would need root access to the VPS for that, the game and the VPS are not tied together when it comes to access

so, I should understand that Penn is fully secured from missusing of softcode, commands and functions that they would prevent causing in the result too big memory usage or other side effects?

@talvo 

Try to understand that Penn is a project with thru the long time I got know it, had become quite important for me. That why I'm trying to help im the development and improvement of it (even if programming isn't my strongest side).

My goal is to help to cause that Penn would become the best and most advanced and secure server of it's kind from all of the existing MUD, MUSH and smililar ones.

**Comment by annelions** [comment]
> so, I should understand that Penn is fully secured from missusing of softcode, commands and functions that they would prevent causing in the result too big memory usage or other side effects?

Such a thing happening is pretty rare these days. But you probably have a better chance of getting struck by lightning than by a random hacker randomly being able to log into _God_ in a brand new MUSH. As already stated, you should be more fearful of your "trusted" Wizards ruining your game than in a random hacker somehow managing to abscond with God in a fresh database.

**Comment by ray73864** [comment]
> Not exactly. He/she does need to attack directly the VPS. It's enough to connect (with terminal) to the server's URL with the port 4201 with a console to connect it
> 

That'll just give them access to the game if they connect to the servers URL with port 4201, they won't get access to your VPS itself.

And if you don't have a GOD password set, the most they can do is damage your game, they can't do any damage to the VPS itself.

> I usually would connect to VPS thru ssh and prefer to connect to the Penn with a separate client

Nothing stopping you using a separate client.

I myself use MobaXterm (in the past I used Putty) to connect to the host server of my development game (Which is a revival of a game I ran over a decade ago).

But I don't connect to the game itself via the terminal, I use the Potato client to connect to the game and maintain the game itself.

If I need to update the game, I connect to the host server, git pull, recompile, reboot the game from within the game and hey presto all done.

> so, I should understand that Penn is fully secured from missusing of softcode, commands and functions that they would prevent causing in the result too big memory usage or other side effects?
> 

Nothing can ever be 100% fully secured, the news has shown us countless times that that is impossible. However, Penn has limits in place that limit how far it can go, you can't create runaway objects in-game as it costs pennies to utilise the queue for certain actions.

If the game does go crazy, you simply log into the host server (VPS or dedicated server, or AWS instance), and kill the game process.

> @talvo
> 
> Try to understand that Penn is a project with thru the long time I got know it, had become quite important for me. That why I'm trying to help im the development and improvement of it (even if programming isn't my strongest side).
> 
> My goal is to help to cause that Penn would become the best, most advanced and secure server of it's kind from all of the existing MUD, MUSH and smililar ones.

The problem is, with all the changes you are trying to get done, it seems like you want Penn to be changed from a MUSH to a MUD.

**Comment by mdziczkowski** [comment]
> Nothing stopping you using a separate client

I personally use Mudlet, wtih gives me a loot possibilities ;-)

> The problem is, with all the changes you are trying to get done, it seems like you want Penn to be changed from a MUSH to a MUD.

actually, you are not correct here ;-)

As I had read, MUSH had evolved from MUD, so it's not that I want to reverse the changes.

It's only a shame that many interesting possibilities from MUD got almost like forgotten thru the time or got split thru many different versions of MUD/MUSH servers.

Unfortunatelly, none of the existing servers have attepted to join them back. I hoped that Penn could at latest try to do such join. ;-)

-------------
All things I post in the ticket's are not intended to argue with anyone or show disrespect, but in oposite. I respect you all for the loot of great work you put into the project development. That thy I try to put some contribution to help you, in hope that my ideas and work get usefull and helps you to make Penn even better ;-)

**Comment by RedFinn** [comment]
> As I had read, MUSH had evolved from MUD, so it's not that I want to reverse the changes.

And yet, constructively, that's what you're asking for. Eliminating the need to hack the db by hand is one of the most important reasons for the development of the internal extension language we use. 

> Unfortunatelly, none of the existing servers have attepted to join them back. I hoped that Penn could at latest try to do such join. ;-)

That's extremely unlikely to happen. Again, we have an internal extension language for this. It's much more elegant and avoids mucking up the database with bad edits. Hand-editing the db is something you only do in an emergency (probably the only reason you should even do it is if you've forgotten the password to #1).

**Comment by annelions** [comment]
>It's only a shame that many interesting possibilities from MUD got almost like forgotten thru the time or got split thru many different versions of MUD/MUSH servers.

I think that many of the things you're asking for were developed after MUDs and MUSHes split. So it's not like they were forgotten. They were deemed unimportant to the main goal of Penn, whatever that goal happened to be at the time. I don't want to discourage anyone from suggesting good ideas but I haven't seen one suggested recently that makes me go "yeah, it'd be cool if MUSHes did that".

**Comment by mdziczkowski** [comment]
@RedFinn 

I didn't meant the hand editing of the database, but the functions, commands, etc. with are existing usually in MUD and were existing in earlier versions of MUSH as well ;-)

@annelions 

In one side is good that MUSH has split from MUD and had gone on with development, but on the other hand, there was no need to resign for some things with MUD was providing, because they weren't distrubing, plus some things wouldn't need to become rewroten from scratch (with was as I assume a loot of coding work). The only thing with could be made was to use the existing ones as a base for the new ones to extend them ;-) This would be easier to switch from mud to MUSH without need to learn anything from start :-p

**Comment by annelions** [comment]
>This would be easier to switch from mud to MUSH without need to learn anything from start :-p

I literally do not understand this point. MUDs and MUSHes serve different purposes. If you want a MUD, why would you even switch to Penn? It's like saying that you need a pickup truck and then using a compact sedan. The truck and the sedan aren't better or worse than one another but they have different features. You wouldn't use a sedan to haul bales of hay around and most pickup trucks make terrible family cars. They have different uses.

**Comment by ray73864** [comment]
> It's only a shame that many interesting possibilities from MUD got almost like forgotten thru the time or got split thru many different versions of MUD/MUSH servers.

Looking at the MUD family tree, PennMUSH (and probably RhostMUSH, I dunno on that one) are based on TinyMUSH, which was based on TinyMUD.

https://mud.fandom.com/wiki/TinyMUD

TinyMUD allowed for player extensible worlds before the MUSH flavour came about, it can be said that Penn already supports the majority of TinyMUD, there's just some extreme cases where it doesn't, and those likely came about after the split.

**Comment by RedFinn** [comment]
> @RedFinn
> 
> I didn't meant the hand editing of the database, but the functions, commands, etc. with are existing usually in MUD and were existing in earlier versions of MUSH as well ;-)

I'm confused. Reading the OP, you ask for a tool that would automatically create databases. The databases get created automatically. Then you said

>As I mentioned earlier, the tool would make the process of world creation and management faster and easier. I cannot imagine myself to manually edit a database with would count for example hundreds lines of code when the world grow up ;-p

You can already do this in the game, without modifying the db externally. Modifying the db while the game is running is asking for trouble, so you'd have to do this offline, but why would you do that, when you can do it on the fly while the game is running?
