### ISSUE TITLE
[feature request] Changes in the databases

### ISSUE THREAD

**Issue by mdziczkowski** [pennmush/pennmush#1391]
My proposal is to do following changes in the databases of Pennmush:

- instead of doing two separate databases (in.db and out.db) should be used only one (if there are two then there is created confusion because in.db oftenly duplicates the out.db

- add database example with all fields explanations
- change the database format to a easier one (for example xml or json)

**Comment by ray73864** [comment]
To answer some of those...

indb is only ever identical to outdb when you are starting up the game.
When the game does its hourly database saves, it saves them to outdb.
When you shutdown the game and then start it up again, the restart script copies outdb to indb and then uses indb to create the in-memory version of the game.

This ensures that you always have a working backup of the game.

Secondly, there is no reason for you to ever manually edit the DB, or even try and create your own DB, hence there has never been a reason to explain what all the fields are, and there's never been a need for an example database because the game creates a brand new minimal database if outdb and indb don't exist.

As to the database format, this has been discussed in the past, it would add a lot of extra overhead moving to a different format and provide no actual benefit.

Again, you aren't supposed to manually edit the database or create your own, that's for the game to do :)

**Comment by talvo** [comment]
Re indb and outdb - that's exactly the point. The game saves to outdb, and when you start it, it copies outdb to indb and runs from that. It's effectively a backup mechanism.

A brief explanation of the db format somewhere wouldn't hurt at all.

The database is currently plain-text, and the format is pretty simple (though admittedly the above would help), making it far easier to look through and edit by hand (and a lot more compact) than an XML or JSON format would be. It also removes the need for external dependancies or a new mess of db-parsing code to parse it.

**Comment by mdziczkowski** [comment]
had proposed this change to make it more compatible with the MMP (MUD Mapping Protocol), that support JSon and xml formats. This way, it would be easier for mappers (like the one used in Mudlet client) to generate basing on it maps.
 
 Another thing in my opinion that tell on the format change adventage is that the plain format is bit chaotic and disallow to recieve the needed flexibility (I'm not sure, but I don't think that this format has changed a much since creation of Penn ;-) ]
