### ISSUE TITLE
WebSocket support and Javascript Client

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pennmush/pennmush#900]
```
Is this a command or @function?
No.

What will the permission restrictions be?
None.

What will this do?
Allow users to connect with a JavaScript client using the WebSocket protocol 
(HTML5 required). Included is a patch for PennMUSH to communicate with the 
WebSocket protocol as well as a basic implementation of a JavaScript client 
with associated HTML/CSS.

Credits for the patch and JavaScript client go to Code Unit #5 (CU5@Successful 
MUSH Task Force) with HTML/CSS improvements by grapenut.

Can this be done in softcode?
No.

```

Original issue reported on code.google.com by `grape...@grapenut.org` on 4 Oct 2013 at 11:43

Attachments:
- [wsclient.tar.gz](https://storage.googleapis.com/google-code-attachments/pennmush/issue-900/comment-0/wsclient.tar.gz)

**Comment by HarryCordewener** [comment]
I highly promote enabling PennMUSH to answer to HTML5 Websocket! Can we at least get that section, even if we don't take up the other sections?

**Comment by tkrajcar** [comment]
@grapenut and @kymoon are the authors here, so this is mostly addressed to them. I also think this is really interesting and cool. Can you open a pull request with just the Penn-side portion of this, so we can easily review the diffs and comment as needed? The JS client should probably go in a repo of your own that we reference from docs, since it's not really part of PennMUSH.

**Comment by talvo** [comment]
See #1007

**Comment by shawnw** [comment]
Now a thing.
