### ISSUE TITLE
unsetq - Regular Expression Edition

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pennmush/pennmush#970]
```
Is this a command or @function?
Function

What will the permission restrictions be?
Same as unsetq()

What will this do?
Be the same as unsetq(), only changing its pattern matching to a single regex.

Can this be done in softcode?
I... I don't think so?
```

Original issue reported on code.google.com by `ad...@twilightdays.org` on 26 Oct 2014 at 6:52

**Comment by talvo** [comment]
Hrm. Not sure how worthwhile this is, now, to be honest.

**Comment by HarryCordewener** [comment]
Some code uses the name of the qregs as a way to get across data even within the qreg name. That's why this is worthwhile. 

For instance, and I know this is an imperfect example as this one is very /simple/, if you have a system that stores the succesful and failed sub-steps in a list of checks... 'filter_step3_success', 'filter_step31_success', 'filter_step33_success', 'filter_step12_fail', 'filter_step33_fail', 'filter_step31_fail'. 

And you want step30 - 32 and failed ones to be unset:
unsetq(.+step3[012]_.+|.+fail) 
vs
unsetq(*step30*)[unsetq(*step31*)][unsetq(*step32*)][unsetq(*fail)]

**Comment by talvo** [comment]
Already quite easily done with something like
unsetq(regraball(listq(),step3[0-9]|fail))
though.

**Comment by HarryCordewener** [comment]
That is very true. I had not thought of that. Guess - ditch this one then. Bit uglier, but not so much that it is /that/ much harder to read.
